### ISSUE TITLE
Crash on Mods Tab

### ISSUE THREAD

**Issue by ghost** [MaatFX/MCFurnace#1]
[latest.log](https://github.com/MaatFX/MCFurnace/files/3543351/latest.log)
I pressed MCFurnace on the mods tab and it crashes

**Comment by 3PGaming** [comment]
I am having an identical issue. It seems to be related to the unzipping of the jar file. See Below:

<details>
 <summary>Minecraft Crash Report</summary>

```
Description: mouseClicked event handler

java.lang.ArrayIndexOutOfBoundsException: 0
	at com.sun.nio.zipfs.ZipPath.getResolvedPath(ZipPath.java:428) ~[zipfs.jar:1.8.0_51] {}
	at com.sun.nio.zipfs.ZipPath.newInputStream(ZipPath.java:645) ~[zipfs.jar:1.8.0_51] {}
	at com.sun.nio.zipfs.ZipFileSystemProvider.newInputStream(ZipFileSystemProvider.java:278) ~[zipfs.jar:1.8.0_51] {}
	at java.nio.file.Files.newInputStream(Files.java:152) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.packs.ModFileResourcePack.func_195766_a(ModFileResourcePack.java:80) ~[?:?] {}
	at net.minecraft.resources.ResourcePack.func_195763_b(SourceFile:53) ~[?:?] {pl:accesstransformer:B}
	at net.minecraftforge.fml.client.gui.GuiModList.lambda$updateCache$12(GuiModList.java:422) ~[?:?] {}
	at net.minecraftforge.fml.client.gui.GuiModList$$Lambda$3341/1253661160.apply(Unknown Source) ~[?:?] {}
	at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.client.gui.GuiModList.updateCache(GuiModList.java:413) ~[?:?] {}
	at net.minecraftforge.fml.client.gui.GuiModList.setSelected(GuiModList.java:397) ~[?:?] {}
	at net.minecraftforge.fml.client.gui.GuiSlotModList$ModEntry.mouseClicked(GuiSlotModList.java:105) ~[?:?] {}
	at net.minecraft.client.gui.widget.list.AbstractList.mouseClicked(AbstractList.java:290) ~[?:?] {pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.INestedGuiEventHandler.mouseClicked(SourceFile:27) ~[?:?] {}
	at net.minecraft.client.MouseHelper.lambda$mouseButtonCallback$0(MouseHelper.java:81) ~[?:?] {pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper$$Lambda$3319/2070690615.run(Unknown Source) ~[?:?] {}
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen.java:441) ~[?:?] {pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper.func_198023_a(MouseHelper.java:79) ~[?:?] {pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper$$Lambda$2883/584203303.invoke(Unknown Source) ~[?:?] {}
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10] {}
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at net.minecraft.client.MainWindow.func_216524_c(SourceFile:291) ~[?:?] {}
	at net.minecraft.client.Minecraft.func_213227_b(Minecraft.java:947) ~[?:?] {pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:907) [?:?] {pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:384) [?:?] {pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:155) [?:?] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.14.4-28.0.93.jar:28.0] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$340/2080643905.call(Unknown Source) [forge-1.14.4-28.0.93.jar:28.0] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-3.2.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:50) [modlauncher-3.2.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:68) [modlauncher-3.2.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:80) [modlauncher-3.2.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-3.2.0.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.sun.nio.zipfs.ZipPath.getResolvedPath(ZipPath.java:428)
	at com.sun.nio.zipfs.ZipPath.newInputStream(ZipPath.java:645)
	at com.sun.nio.zipfs.ZipFileSystemProvider.newInputStream(ZipFileSystemProvider.java:278)
	at java.nio.file.Files.newInputStream(Files.java:152)
	at net.minecraftforge.fml.packs.ModFileResourcePack.func_195766_a(ModFileResourcePack.java:80)
	at net.minecraft.resources.ResourcePack.func_195763_b(SourceFile:53)
	at net.minecraftforge.fml.client.gui.GuiModList.lambda$updateCache$12(GuiModList.java:422)
	at net.minecraftforge.fml.client.gui.GuiModList$$Lambda$3341/1253661160.apply(Unknown Source)
	at java.util.Optional.map(Optional.java:215)
	at net.minecraftforge.fml.client.gui.GuiModList.updateCache(GuiModList.java:413)
	at net.minecraftforge.fml.client.gui.GuiModList.setSelected(GuiModList.java:397)
	at net.minecraftforge.fml.client.gui.GuiSlotModList$ModEntry.mouseClicked(GuiSlotModList.java:105)
	at net.minecraft.client.gui.widget.list.AbstractList.mouseClicked(AbstractList.java:290)
	at net.minecraft.client.gui.INestedGuiEventHandler.mouseClicked(SourceFile:27)
	at net.minecraft.client.MouseHelper.lambda$mouseButtonCallback$0(MouseHelper.java:81)
	at net.minecraft.client.MouseHelper$$Lambda$3319/2070690615.run(Unknown Source)

-- Affected screen --
Details:
	Screen name: net.minecraftforge.fml.client.gui.GuiModList
Stacktrace:
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen.java:441)
	at net.minecraft.client.MouseHelper.func_198023_a(MouseHelper.java:79)
	at net.minecraft.client.MouseHelper$$Lambda$2883/584203303.invoke(Unknown Source)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174)
	at net.minecraft.client.MainWindow.func_216524_c(SourceFile:291)
	at net.minecraft.client.Minecraft.func_213227_b(Minecraft.java:947)
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:907)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:384)
	at net.minecraft.client.main.Main.main(SourceFile:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$340/2080643905.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:50)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:68)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:80)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 677538256 bytes (646 MB) / 2175270912 bytes (2074 MB) up to 5163712512 bytes (4924 MB)
	CPUs: 6
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx5539m -Xms256m -XX:PermSize=256m
	ModLauncher: 3.2.0+60+b86c1d4
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-1.0.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.14.4-28.0.93.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.14.4-28.0.93.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-1.0.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.14.4-28.0.93.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.14.4-28.0.93.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.14.4-28.0.93.jar fml TRANSFORMATIONSERVICE 
	FML: 28.0
	Forge: net.minecraftforge:28.0.93
	FML Language Providers: 
		javafml@28.0
		minecraft@1
	Mod List: 
		angelring-1.14.4-1.0.1.jar Angel Ring {angelring@1.0.1 DONE}
		container-1.14.4-0.10.12.jar Container {container@1.14.4-0.10.12 DONE}
		Cyclic-1.14.4-0.0.10.jar Cyclic {cyclic@1.14.4-0.0.10 DONE}
		EnderBags-1.14.4-4.2.0.jar Ender Bags {ender_bags@4.2.0 DONE}
		essentials-1.14.4-2.4.1.jar Essentials {essentials@1.14.4-2.4.1 DONE}
		FastLeafDecay-v17.jar FastLeafDecay {fastleafdecay@v17 DONE}
		hoppersplus-1.1-1.14.4.jar Hoppers Plus {hoppersplus@1.0 DONE}
		ironchest-1.14.4-9.0.4.jar Iron Chests {ironchest@1.14.3-9.0.3 DONE}
		jei-1.14.4-6.0.0.11.jar Just Enough Items {jei@6.0.0.11 DONE}
		LinkedDestruction-1.14.4-0.6.0.jar Linked Destruction {linkeddestruction@1.14.4-0.6.0.9999 DONE}
		MCFurnace-1.14.4-DEV-1.2.1.jar MCFurnace {mcfurnace@1.0 DONE}
		Placebo-1.14.4-2.2.0.jar Placebo {placebo@2.2.0 DONE}
		randomenchants-2.1.0.jar Random Enchants {randomenchants@2.1.0 CONSTRUCT}
		RingOfGrowth-1.14.4-1.0.11.jar Ring of Growth {ring_of_growth@1.0.11 DONE}
		RingOfTeleport-1.14.4-1.0.9.jar Ring of Teleport {ring_of_teleport@1.0.9 DONE}
		shulkerbox-1.7.0.jar Advanced Shulkerboxes {shulkerbox@1.7.0 DONE}
		simpleores-1.14.4-2.0.6.0.jar Simple Ores {simpleores@1.14.4-2.0.6.0 DONE}
		switchbow-1.5.7.jar Switch-Bow {switchbow@1.5.7 DONE}
		torcherino-9.0.3.jar Torcherino {torcherino@9.0.3 DONE}
		ultra_amplified_mod-1.14.4-0.6.6.jar Ultra Amplified Mod {ultra_amplified_mod@0.6.6 DONE}
		usefulmending-1.0.jar Useful Mending {usefulmending@1.0 DONE}
		weapon_craftery-1.14.4-1.0-Beta-4.jar Weapon Craftery {weapon_craftery@1.14.4-1.0-Beta-4 DONE}
		forge-1.14.4-28.0.93-universal.jar Forge {forge@28.0.93 CONSTRUCT}
		forge-1.14.4-28.0.93-client.jar Minecraft {minecraft@1.14.4 CONSTRUCT}
	Launched Version: forge-28.0.93
	LWJGL: 3.2.2 build 10
```
</details>

I hope this help a bit. I understand that mod writing, especially the config entries, is kind of broken until forge re-enables them. But in the meantime, may I suggest removing any link to them?

**Comment by 3PGaming** [comment]
I've done a little research and found this: https://bugs.eclipse.org/bugs/show_bug.cgi?id=527569

Apparently, if you build with eclipse, you need to make sure your JDK/JRE is up to date. I believe there is an issue with your java library versions.

**Comment by MaatFX** [comment]
well, check the new version and tell me if it happens as well. I don't have this problem
